language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install libexpat1 libexpat1-dev libicu-dev
before_script:
  - pwd
  - mysql -e "CREATE DATABASE piball;"
  - mysql piball < tests/fixtures/piball.sql
  - mysql -e "UPDATE mysql.user SET password=PASSWORD('travis') WHERE user='travis'; FLUSH PRIVILEGES"
notifications:
  email:
    recipients:
      - notifications@andrelademann.de
