language: node_js
node_js:
  - "0.6.20"
  - "0.8"
  - "0.10"
  - "0.11"
  - "0.12"
before_script:
  - pwd
  - mysql -e "CREATE DATABASE foosball;"
  - mysql foosball < tests/fixtures/foosball.sql
  - mysql -e "UPDATE mysql.user SET password=PASSWORD('travis') WHERE user='travis'; FLUSH PRIVILEGES"
