language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libicu-dev
before_script:
  - pwd
  - mysql -e "CREATE DATABASE foosball;"
  - mysql foosball < tests/fixtures/foosball.sql
  - mysql -e "UPDATE mysql.user SET password=PASSWORD('travis') WHERE user='travis'; FLUSH PRIVILEGES"
